### ISSUE TITLE
Login with github: excessive required permissions

### ISSUE THREAD

**Issue by JuanjoA** [dcodesdev/rustfinity.com#31]
Hi, firts of all, thank you for trying to bring rust to more people.

I was going to try the platform, but the permissions required by the app seem excessive to me, specifically the one that indicates:

_Know which resources you can access_

Why is it necessary?

Regards.

**Comment by dcodesdev** [comment]
Had this at the back of my mind for a while.

Thanks for bringing it to my attention, I fixed it, you can now sign up without giving any extra access to the app.
