### ISSUE TITLE
Allow to see all test logs

### ISSUE THREAD

**Issue by JuanjoA** [dcodesdev/rustfinity.com#32]
Hi, I trying the course.
When there is an error in the tests, and the logs are displayed, they are not displayed in complete form. The lines are cut off.
It would be nice to have scrollbars.
For now I am not fluent in the rust language, maybe in the near future I will be able to propose a PR.
Attached is a screenshot.
![image](https://github.com/user-attachments/assets/98d9c9d0-04d1-4f9b-af6c-7ca0b34425f0)

By the way, the test fails me by not finding a variable that is there (_Variable height was not declared_). This occurs when we define the variable type, if I do not define it, it works.

Thanks.

**Comment by dcodesdev** [comment]
Thank you very much for raising the issue, this is fixed now, you can try it.
