### ISSUE TITLE
Typo: docs/data-types

### ISSUE THREAD

**Issue by abeixiaolu** [dcodesdev/rustfinity.com#39]
<img width="1098" alt="图片" src="https://github.com/user-attachments/assets/060e4b5c-077c-47ef-a141-fa9623b697d0">
It may be: In this example, by default the type of the array `seasons` would be inferred as `[&str; 4]`, but we are telling the Rust compiler to use the type `[&str; 4]` explicitly.

**Comment by dcodesdev** [comment]
Fixed it.

Thanks a lot for raising the issue.
