### ISSUE TITLE
⚠️ Found a bug that doesn't give me the flag ✅  when I complete a lesson

### ISSUE THREAD

**Issue by AntonioBerna** [dcodesdev/rustfinity.com#57]
I found this:

![Schermata 2024-12-02 alle 08 20 25](https://github.com/user-attachments/assets/4b6ef11a-4ccd-4657-9add-b42569dcb527)

in particular the `Control flow` section don't assign me the flag ✅

**Comment by dcodesdev** [comment]
Thanks for the feedback, but you'll get the check once you finish the lessons under it.

**Comment by AntonioBerna** [comment]
> Thanks for the feedback, but you'll get the check once you finish the lessons under it.

Thanks for responding so quickly. Unfortunately I passed the sub-lessons and it still doesn't give the flag.

![Schermata 2024-12-02 alle 08 51 36](https://github.com/user-attachments/assets/ade84d20-ed18-4ec9-99c6-e61d42bf0ec2)

**Comment by AntonioBerna** [comment]
> It's because you haven't finished the **Control Flow** page itself, I know you did read all of it, but the way it works is after you stay on a page for 10 seconds and scroll to the bottom it will mark it as read.

Ok thank you. Have a good day!
